# Generated by Django 3.0 on 2021-09-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField(verbose_name='Data do dia')),
                ('horario', models.TimeField(verbose_name='Hora')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data de agendamento')),
                ('medico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.IntegerField(default=0)),
                ('nome_medico', models.CharField(max_length=100)),
                ('especialidade_medico', models.CharField(max_length=100)),
            ],
        ),
    ]
