# Generated by Django 3.0 on 2021-10-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210919_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medicos',
            name='telefone',
            field=models.PositiveIntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='crm',
            field=models.IntegerField(null=None, unique=True),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidade_medico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Especialidade'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='nome_medico',
            field=models.CharField(max_length=255, null=None),
        ),
    ]
