# Generated by Django 3.0 on 2021-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211003_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='telefone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
