# Generated by Django 3.0 on 2021-10-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211003_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='telefone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
