# Generated by Django 3.0 on 2021-10-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211003_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade_medico',
            new_name='especialidade',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='nome_medico',
            new_name='nome',
        ),
    ]
